apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: django-web-admin
build:
  artifacts:
    - image: xdot2012/circle_ci_python
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - infra/k8s/django.yaml
    - infra/k8s/ingress-srv.yaml
