version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build:
    docker:
      - image: cimg/base:2021.04
    
    steps:
      - checkout

      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            sudo mv /tmp/docker/* /usr/bin

      - run:
          name: Install Docker Compose
          command: |
            set -x
            sudo chmod 777 /usr/local/bin/docker-compose
            sudo curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose

      - setup_remote_docker
      
      - run:
          name: Start container
          command: |
            set -x
            docker-compose up -d
            docker container run --network container:django-server \
            docker.io/jwilder/dockerize \
            -wait http://localhost:8080/healthcheck \
            -wait-retry-interval 2s \
            -timeout 20s

workflows:
  sample:
    jobs:
      - build
