version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build:
    docker:
      - image: cimg/python:3.10.2

    steps:
      - run:
          name: Start container and verify it's working
          command: |
            set -x
            docker-compose up -d

workflows:
  sample:
    jobs:
      - build
