version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.10.1
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            sudo apt-get update -y
            sudo apt-get -y install binutils libproj-dev gdal-bin libjpeg-dev zlib1g-dev rabbitmq-server
            pip install --upgrade pip ipython redis celery flower gunicorn
      - run:
          name: install development requirements
          command: |
            pip install -r code/requirements-dev.txt
      - run:
          name: install requirements
          command: |
            pip install -r code/requirements.txt
      - run:
          name: run tests
          command: python code/manage.py test

workflows:
  build-workflow:
    jobs:
      - build