version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.10.1
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            sudo apt-get -y install binutils libproj-dev gdal-bin \
            sudo apt-get -y install libjpeg-dev \
            sudo apt-get -y install zlib1g-dev \
            sudo apt-get -y install rabbitmq-server \
            pip install --upgrade pip \
            pip install ipython \
            pip install redis \
            pip install celery \
            pip install flower \
            pip install gunicorn \
            pip install -r code/requirements-dev.txt code/requirements.txt
      - run:
          name: run tests
          command: python manage.py test

workflows:
  build-and-test-workflow:
    jobs:
      - test-and-lint